Update CD-Deploy.yml

diff --git a/.github/workflows/CD-Deploy.yml b/.github/workflows/CD-Deploy.yml
--- a/.github/workflows/CD-Deploy.yml
+++ b/.github/workflows/CD-Deploy.yml
@@ -248,6 +248,33 @@ jobs:
             ${{ runner.os }}-mint-
 
       # ====================
+      # Setup SSH Agent for fastlane match or private pod repos (git clone private repo)
+      # 啟用 SSH Agent 並加入私鑰
+      - name: Setup SSH Agent
+        uses: webfactory/ssh-agent@v0.9.0
+        with:
+          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+
+      # 設定 github.com 為 known host
+      - name: Add GitHub to known_hosts
+        run: |
+          mkdir -p ~/.ssh
+          ssh-keyscan github.com >> ~/.ssh/known_hosts
+
+      # For Demo Test
+      # 驗證 SSH Agent 設定成功，可以 git clone private repo
+      - name: Clone another private repo
+        run: |
+          git clone git@github.com:ZhgChgLi/github-actions-ci-cd-demo-certificates.git ./fakeMatch/
+
+          if [ -d "./fakeMatch/.git" ]; then
+            echo "✅ Repo cloned successfully into ./fakeMatch/"
+          else
+            echo "❌ SSH Agent Setup failed."
+            exit 1
+          fi
+          
+      # ====================
 
       # 專案 Setup & 依賴安裝
       - name: Setup & Install Dependency
