Update CI-Testing.yml

diff --git a/.github/workflows/CI-Testing.yml b/.github/workflows/CI-Testing.yml
--- a/.github/workflows/CI-Testing.yml
+++ b/.github/workflows/CI-Testing.yml
@@ -153,7 +153,7 @@ jobs:
           # mint run yonaskolb/XcodeGen --quiet
           # bundle exec pod install
           # ...
-          # 等等 setup 指令
+          # 等等 install 指令
           make install
 
       # 執行 Fastlane Unit 測試 Lane
@@ -166,12 +166,68 @@ jobs:
           DEVELOPER_DIR: "/Applications/Xcode_${{ steps.read_xcode_version.outputs.xcode_version }}.app/Contents/Developer"
           SIMULATOR_NAME: ${{ vars.SIMULATOR_NAME }}
           RUNNER_NAME: ${{ runner.name }}
+          
+          # 提升 XCodebuild 指令 timeout 時間, retry 次數
+          # 因為機器 Loading 比較大的時候可能 3 次就失敗了
+          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60
+          FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 10
         run: |
 
           # 如果是 self-hosted 在同一台機器起多個 Runner 會出現搶模擬器的問題 (文章後會講)
           # 要避免這問題建議將模擬名稱命名成 Runner 名稱，每個 Runner 都設一個模擬器，這樣就不會互搶導致測試失敗
           # e.g. bundle exec fastlane run_unit_tests device:"${RUNNER_NAME} (18.4)"
-          # 這邊是用 GitHub Hosted Runner 沒這問題，所以直接用
-          bundle exec fastlane run_unit_tests device:"${SIMULATOR_NAME}"
-          
+          # 這邊是用 GitHub Hosted Runner 沒這問題，所以直接用 device:"${SIMULATOR_NAME}"
 
+          # 發生錯誤不直接退出並將所有輸出都寫入 temp/testing_output.txt 檔案
+          # 後續我們會分析檔案內容區分出是 Build Failed 還是 Test Failed，Comment 不同訊息到 PR
+          set +e
+          
+          # EXIT_CODE 儲存執行結果的 exit code.
+          # 0 = OK
+          # 1 = exit
+          EXIT_CODE=0
+          
+          # 所有輸出都寫入檔案
+          bundle exec fastlane run_unit_tests device:"${SIMULATOR_NAME}" | tee "$RUNNER_TEMP/testing_output.txt"
+          # 如果目前 EXIT_CODE 是 0，則將 ${pipestatus[1]} 賦值給 EXIT_CODE
+          [[ $EXIT_CODE -eq 0 ]] && EXIT_CODE=${pipestatus[1]}
+
+          # 恢復出錯就退出
+          set -e
+
+          # 讀取 Testing Output
+          TESTING_OUTPUT=$(<"$RUNNER_TEMP/testing_output.txt")
+
+          # Testing Output 不為空
+          if [[ -n "$TESTING_OUTPUT" ]]; then
+              # 如果 Testing Output 包含 "Error building"，則設 is_building_error=true 給 Actions 環境變數，為 Build 就失敗
+              # 如果 Testing Output 包含 "Tests have failed"，則設 is_test_error=true 給 Actions 環境變數，為測試失敗
+
+              if [[ $TESTING_OUTPUT == *"Error building"* ]]; then
+                  echo "is_building_error=true" >> $GITHUB_OUTPUT
+              elif [[ $TESTING_OUTPUT == *"Tests have failed"* ]]; then
+                  echo "is_test_error=true" >> $GITHUB_OUTPUT
+              fi
+          fi
+
+          # 恢復 Exit Code Output
+          exit $EXIT_CODE
+          
+      # ========== Handle Result Steps ==========
+      
+      # 解析 *.junit 測試報告，並標記結果、Comment(如果是 PR 的話)
+      - name: Publish Test Report
+        # 直接復用別人寫好的 .junit Paser Actions: https://github.com/mikepenz/action-junit-report
+        uses: mikepenz/action-junit-report@v5
+        # if:
+        # 上一步(Testing) success or
+        # 上一步(Testing) failed and is_test_error (build failed 不執行這個 step)
+        if: ${{ (steps.testing.outputs.is_test_error == 'true' && failure()) || success() }}
+        with:
+          check_name: "Testing Report"
+          comment: true
+          updateComment: false
+          require_tests: true
+          detailed_summary: true
+          report_paths: "./Product/fastlane/test_output/*.junit"
+      
